#ifndef RENDER_TYPES_H
#define RENDER_TYPES_H

#include <dxgiformat.h>
#include "../../libs/number_types.h"

enum Primitive_Type {
	PRIMITIVE_TYPE_UNKNOWN,
	PRIMITIVE_TYPE_POINT,
	PRIMITIVE_TYPE_LINE,
	PRIMITIVE_TYPE_TRIANGLE,
	PRIMITIVE_TYPE_PATCH
};

enum Resource_Usage {
	RESOURCE_USAGE_DEFAULT,
	RESOURCE_USAGE_UPLOAD,
	RESOURCE_USAGE_READBACK
};

enum Resource_State {
	RESOURCE_STATE_UNKNOWN,
	RESOURCE_STATE_COMMON,
	RESOURCE_STATE_GENERIC_READ,
	RESOURCE_STATE_COPY_DEST,
	RESOURCE_STATE_COPY_SOURCE,
	RESOURCE_STATE_PRESENT,
	RESOURCE_STATE_RENDER_TARGET,
	RESOURCE_STATE_DEPTH_WRITE,
	RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
	RESOURCE_STATE_ALL_SHADER_RESOURCE,
	RESOURCE_STATE_UNORDERED_ACCESS,
};

enum Texture_Dimension {
	TEXTURE_DIMENSION_UNKNOWN,
	TEXTURE_DIMENSION_1D,
	TEXTURE_DIMENSION_2D,
	TEXTURE_DIMENSION_3D
};

enum Sampler_Filter {
	SAMPLER_FILTER_POINT,
	SAMPLER_FILTER_LINEAR,
	SAMPLER_FILTER_ANISOTROPIC
};

enum Address_Mode {
	ADDRESS_MODE_WRAP,
	ADDRESS_MODE_MIRROR,
	ADDRESS_MODE_CLAMP,
	ADDRESS_MODE_BORDER,
};

enum GPU_Heap_Type {
	GPU_HEAP_TYPE_DEFAULT,
	GPU_HEAP_TYPE_UPLOAD,
	GPU_HEAP_TYPE_READBACK
};

enum GPU_Heap_Content {
	GPU_HEAP_CONTAIN_BUFFERS,
	GPU_HEAP_CONTAIN_BUFFERS_AND_TEXTURES,
	GPU_HEAP_CONTAIN_RT_DS_TEXTURES
};

enum Shader_Register {
	CONSTANT_BUFFER_REGISTER = 0,
	SHADER_RESOURCE_REGISTER = 1,
	UNORDERED_ACCESS_REGISTER = 2,
	SAMPLER_REGISTER = 3
};

enum Pipeline_Type {
	PIPELINE_TYPE_UNKNOWN,
	PIPELINE_TYPE_COMPUTE,
	PIPELINE_TYPE_GRAPHICS
};

enum Command_List_Type {
	COMMAND_LIST_TYPE_DIRECT = 0,
	COMMAND_LIST_TYPE_BUNDLE = 1,
	COMMAND_LIST_TYPE_COMPUTE = 2,
	COMMAND_LIST_TYPE_COPY = 3
};

enum Fill_Type {
	FILL_TYPE_WIREFRAME,
	FILL_TYPE_SOLID
};

enum Cull_Type {
	CULL_TYPE_UNKNOWN,
	CULL_TYPE_FRONT,
	CULL_TYPE_BACK
};

enum Blend_Option {
	BLEND_ZERO,
	BLEND_ONE,
	BLEND_SRC_COLOR,
	BLEND_INV_SRC_COLOR,
	BLEND_SRC_ALPHA,
	BLEND_INV_SRC_ALPHA,
	BLEND_DEST_ALPHA,
	BLEND_INV_DEST_ALPHA,
	BLEND_DEST_COLOR,
	BLEND_INV_DEST_COLOR,
	BLEND_SRC_ALPHA_SAT,
	BLEND_BLEND_FACTOR,
	BLEND_INV_BLEND_FACTOR,
	BLEND_SRC1_COLOR,
	BLEND_INV_SRC1_COLOR,
	BLEND_SRC1_ALPHA,
	BLEND_INV_SRC1_ALPHA
};

enum Blend_Operation {
	BLEND_OP_ADD,
	BLEND_OP_SUBTRACT,
	BLEND_OP_REV_SUBTRACT,
	BLEND_OP_MIN,
	BLEND_OP_MAX
};

enum Stencil_Operation {
	STENCIL_OP_KEEP,
	STENCIL_OP_ZERO,
	STENCIL_OP_REPLACE,
	STENCIL_OP_INCR_SAT,
	STENCIL_OP_DECR_SAT,
	STENCIL_OP_INVERT,
	STENCIL_OP_INCR,
	STENCIL_OP_DECR
};

enum Comparison_Func {
	COMPARISON_NEVER,
	COMPARISON_LESS,
	COMPARISON_EQUAL,
	COMPARISON_LESS_EQUAL,
	COMPARISON_GREATER,
	COMPARISON_NOT_EQUAL,
	COMPARISON_GREATER_EQUAL,
	COMPARISON_ALWAYS
};

enum Depth_Write {
	DEPTH_WRITE_ZERO,
	DEPTH_WRITE_ALL
};
#endif
