#ifndef RENDER_TYPES_H
#define RENDER_TYPES_H

#include <dxgiformat.h>
#include "../../libs/number_types.h"

enum Primitive_Type {
	PRIMITIVE_TYPE_UNKNOWN,
	PRIMITIVE_TYPE_POINT,
	PRIMITIVE_TYPE_LINE,
	PRIMITIVE_TYPE_TRIANGLE,
	PRIMITIVE_TYPE_PATCH
};

enum Resource_Usage {
	RESOURCE_USAGE_DEFAULT,
	RESOURCE_USAGE_UPLOAD,
	RESOURCE_USAGE_READBACK
};

enum Resource_State {
	RESOURCE_STATE_UNKNOWN,
	RESOURCE_STATE_COMMON,
	RESOURCE_STATE_GENERIC_READ,
	RESOURCE_STATE_COPY_DEST,
	RESOURCE_STATE_COPY_SOURCE,
	RESOURCE_STATE_PRESENT,
	RESOURCE_STATE_RENDER_TARGET,
	RESOURCE_STATE_DEPTH_WRITE,
	RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
	RESOURCE_STATE_ALL_SHADER_RESOURCE,
};

enum Texture_Dimension {
	TEXTURE_DIMENSION_UNKNOWN,
	TEXTURE_DIMENSION_1D,
	TEXTURE_DIMENSION_2D,
	TEXTURE_DIMENSION_3D
};

enum Sampler_Filter {
	SAMPLER_FILTER_POINT,
	SAMPLER_FILTER_LINEAR,
	SAMPLER_FILTER_ANISOTROPIC
};

enum Address_Mode {
	ADDRESS_MODE_WRAP,
	ADDRESS_MODE_MIRROR,
	ADDRESS_MODE_CLAMP,
	ADDRESS_MODE_BORDER,
};

enum Command_List_Type {
	COMMAND_LIST_TYPE_DIRECT,
	COMMAND_LIST_TYPE_BUNDLE,
	COMMAND_LIST_TYPE_COMPUTE,
	COMMAND_LIST_TYPE_COPY
};

enum GPU_Heap_Type {
	GPU_HEAP_TYPE_DEFAULT,
	GPU_HEAP_TYPE_UPLOAD,
	GPU_HEAP_TYPE_READBACK
};

enum GPU_Heap_Content {
	GPU_HEAP_CONTAIN_BUFFERS,
	GPU_HEAP_CONTAIN_BUFFERS_AND_TEXTURES,
	GPU_HEAP_CONTAIN_RT_DS_TEXTURES
};

enum Shader_Register {
	CONSTANT_BUFFER_REGISTER = 0,
	SHADER_RESOURCE_REGISTER = 1,
	UNORDERED_ACCESS_REGISTER = 2,
	SAMPLER_REGISTER = 3
};

enum Pipeline_Type {
	PIPELINE_TYPE_UNKNOWN,
	PIPELINE_TYPE_COMPUTE,
	PIPELINE_TYPE_GRAPHICS
};

enum Command_List_Type {
	COMMAND_LIST_TYPE_DIRECT,
	COMMAND_LIST_TYPE_BUNDLE,
	COMMAND_LIST_TYPE_COMPUTE,
	COMMAND_LIST_TYPE_COPY
};

u32 dxgi_format_size(DXGI_FORMAT format);
#endif
